### ISSUE TITLE
findup-sync security updates

### ISSUE THREAD

**Issue by BrandonCopley** [tkellen/js-matchdep#21]
findup-sync should be updated to the most recent version to raise the version of minimatch (included with findup-sync) to remove a potential RegEx DOS vulnerability.

**Comment by tkellen** [comment]
Would you mind submitting a PR? I'd be happy to land and cut a release if all the tests pass.

**Comment by phated** [comment]
These bumps were major so we need to be careful. The vulnerability doesn't really effect this module.

**Comment by phated** [comment]
These dependencies have been updated and published as 2.0.0
